return {
	["Starter Island Quest"] = {
		"Soldier",
		"Clown Pirate",
		"Smoky",
		"Tashi",
	},
	["Pirate Island Quest"] = {
		"Clown Swordman",
		"The Clown",
	},
	["Soldier Town Quest"] = {
		"Commander",
		"Captain",
		"The Barbaric",
	},
	["Chef Ship Quest"] = {
		"Trainer Chef",
		"Dark Leg",
		"Dory",
	},
	["Desert Island Quest"] = {
		"Candle Man",
		"Sand Bandit",
		"Bomb Man",
		"Desert Marauder",
		"King of Sand",
	},
	["Skyland Quest"] = {
		"Sky Soldier",
		"Cloud Warrior",
	},
	["Skyland 2 Quest"] = {
		"Ball Man",
		"Rumble Man",
	},
	["Bubbleland Quest"] = {
		"Elite Soldier",
		"Leader",
		"Pasta",
	},
	["Lobby Island Quest"] = {
		"Naval personnel",
		"Wolf",
		"Giraffe",
	},
	["Lobby Island Quest 2"] = {
		"Nautical soldier",
		"Naval soldier",
		"Leo",
	},
	["Zombie Island Quest"] = {
		"Zombie",
		"Elite Zombie",
		"Revenant",
		"Shadow Master",
	},
	["War Island Quest"] = {
		"New World Pirate",
		"Cutlass Pirate",
		"Rear Admiral",
		"True Karate Fishman",
		"Quake Woman",
	},
	["Fishland Quest"] = {
		"Fishman",
		"Combat Fishman",
		"Sword Fishman",
		--"Soldier Fishman",
		"Seasoned Fishman",
	},
	["Japan 1 Quest"] = {
		"Beast Pirate",
		"Beast SwordMan",
		"Gazelle Man",
	},
	["Japan 2 Quest"] = {
		"Bandit Beast Pirate",
		"Powerful Beast Pirate",
		"Violet Samurai",
	},
	["Japan 3 Quest"] = {
		"Duke",
		"Magician",
		"Kitsune Samurai",
	},
	["Japan 4 Quest"] = {
		"Elite Beast Pirate",
		"Bear Man",
		"Bean",
	},
	["Japan 5 Quest"] = {
		"Meji",
		"Petra",
	},
	["Japan 6 Quest"] = {
		"Kappa",
		"Joey",
	},
	["Skull Island Quest"] = {
		"Skull Pirate",
		"Elite Skeleton",
	},
	["Desert 2nd Quest"] = {
		"Desert Thief",
		"Anubis",
		"Pharaoh",
		"Flame User",
	},
	["Loaf 1 Quest"] = {
		"Chess Soldier",
		"Sunken Vessel",
		"Biscuit Man",
	},
	["Loaf 2 Quest"] = {
		"Dough Master",
	},
	["Shred Endangering Quest"] = {
		"Azlan",
		"The Volcano",
		--"The Ice King",
		--"The Crimson Demon",
	},
	["Skull Pirate Island Quest"] = {
		"Dark Beard Servant",
		"Supreme Swordman",
		"Sally",
	},
	["Soldier Head Quater 1 Quest"] = {
		"Vice Admiral",
		"Pondere",
	},
	["Soldier Head Quater 2 Quest"] = {
		"Hefty",
		--"Lucidus",
	},
	["Fiore 1 Quest"] = {
		"Fiore Gladiator",
		"Fiore Fighter",
	},
	["Fiore 2 Quest"] = {
		"Fiore Pirate",
		"Lomeo",
	},
	["Fiore 3 Quest"] = {
		"Prince Aria",
		"Devastate",
		"Physicus",--
		"Floffy",--
	},
	["Fiore 4 Quest"] = {
		"Dead Troupe",
		"Dead Troupe Captain",
		"Ryu",
	},
}
