return {
		["Starter Island Quest"] = {
			"Soldier",
			"Clown Pirate",
			"Smoky",
			"Tashi",
		},
		["Pirate Island Quest"] = {
			"Clown Swordman",
			"The Clown",
		},
		["Soldier Town Quest"] = {
			"Commander",
			"Captain",
			"The Barbaric",
		},
		["Chef Ship Quest"] = {
			"Trainer Chef",
			"Dark Leg",
			"Dory",
		},
		["Desert Island Quest"] = {
			"Candle Man",
			"Sand Bandit",
			"Bomb Man",
			"Desert Marauder",
			"King of Sand",
		},
		["Bubbleland Quest"] = {
			"Elite Soldier",
			"High-class Soldier",
			"Leader",
			"Pasta",
		},
	}
